"""Initial revision

Revision ID: 619c09c0f727
Revises: 5ad20efe0508
Create Date: 2025-05-18 18:13:11.970381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619c09c0f727'
down_revision: Union[str, None] = '5ad20efe0508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'skills', ['title'])
    op.create_unique_constraint(None, 'skills', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_constraint(None, 'skills', type_='unique')
    # ### end Alembic commands ###
