"""Initial revision

Revision ID: 6b4373b2b070
Revises: 36cad7ed8067
Create Date: 2025-05-21 19:33:57.602713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4373b2b070'
down_revision: Union[str, None] = '36cad7ed8067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('skills_user_id_fkey', 'skills', type_='foreignkey')
    op.drop_column('skills', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('skills_user_id_fkey', 'skills', 'users', ['user_id'], ['telegram_id'])
    # ### end Alembic commands ###
