"""Initial revision

Revision ID: 7cd0a04b8919
Revises: 6b4373b2b070
Create Date: 2025-05-21 19:37:48.855416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd0a04b8919'
down_revision: Union[str, None] = '6b4373b2b070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skills',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    op.drop_table('userskills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userskills',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='userskills_skill_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name='userskills_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id', name='userskills_pkey')
    )
    op.drop_table('user_skills')
    # ### end Alembic commands ###
